### ISSUE TITLE
[Question] remove uow dependency?

### ISSUE THREAD

**Issue by xixiaofinland** [rsoesemann/apex-domainbuilder#2]
Good stuff Robert as always!

It is lovely that uow speeds DML actions up, but for many of us, bringing in parts of fflib into production code needs approval.

Also the main goal of this repo is to have a clean testBuilder, while uow is only nice-to-have feature. Wonder if it is better to decouple uow out? My 5cents.

Br,
Xi

**Comment by rsoesemann** [comment]
Feel free to fork and get rid of it. I'd be more than happy to have no dependency. But as monstrous as the fflib is as helpful is it's power.
