### ISSUE TITLE
How to handle circular relationship?

### ISSUE THREAD

**Issue by JeroenSfdc** [rsoesemann/apex-domainbuilder#5]
I'd like to use Domain Builder with circular relationships. 

Object `ParentObject__c` with has a lookup to `ChildObject__c`
Object `ChildObject__c` has a M/D relation with `ParentObject__c`

```
@IsTest
public class Parent_t extends DomainBuilder {

    public Parent_t() {
        super(ParentObject__c.SObjectType);
    }
}
```

```
@IsTest
public class Child_t extends DomainBuilder{
	
    public Child_t(Parent_t p) {
        super(ChildObject__c.SObjectType);
        setParent(ChildObject__c.Parent__c, p);
    }
    
	public Child_t add(Parent_t p) {
        return (Child_t) p.setParent(ParentObject__c.Child__c, this);
    } 
}
```

```
@IsTest
private class TestDomainBuilder {
    
    @TestSetup
    private static void setup() {
    	Parent_t p = new Parent_t();
	Child_t c = new Child_t(p);
        //p.persist(); // this does not help as workaround
        c.add(p);
        p.persist();
    }
    
    @IsTest
    private static void testSetup() {
        System.assertEquals(1, [SELECT Id FROM ParentObject__c].size());
        System.assertEquals(1, [SELECT Id FROM ChildObject__c].size());      
	System.assertEquals(1, [SELECT Id FROM ParentObject__c WHERE Child__c != NULL].size());      
    }
}
```

Test will fail: 
```
System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Parent__c]: [Parent__c]
```

If I persist before adding the circular reference, the error is gone but the assert fails.

**Comment by JeroenSfdc** [comment]
@rsoesemann is this possible with Apex Domain Builder pattern?

**Comment by rsoesemann** [comment]
@JeroenSfdc: Not yet. But you could add adjusting the Domainbuilder to keep track of such circles and do a second DML. We did something similar for self references in https://github.com/rsoesemann/apex-domainbuilder/pull/4/files.

I currently don't have time to try it myself. Would you like to try it?

I added a test documenting that non working case here https://github.com/rsoesemann/apex-domainbuilder/blob/master/force-app/main/default/classes/DomainBuilder_Test.cls#L138

**Comment by JeroenSfdc** [comment]
I'm currently very much tied-up. Happy to jump on it at some point. It will greatly improve the apex domain builder approach. For now verification that this is limitation indeed is enough. Unfortunately we have org with many of such circular refs between objects.
